# Generated by Django 5.0.1 on 2024-01-24 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_reporter_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['headline']},
        ),
        migrations.AddField(
            model_name='article',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 2, 22, 1, 359611, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 2, 22, 1, 359611, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='reporter',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 2, 22, 1, 358614, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='reporter',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 2, 22, 1, 358614, tzinfo=datetime.timezone.utc)),
        ),
    ]
