# Generated by Django 5.0.1 on 2024-01-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_place_restaurant_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
