# Generated by Django 5.0.1 on 2024-01-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_employee_proxyemployee1'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyEmployee2',
            fields=[
            ],
            options={
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('polls.employee',),
        ),
        migrations.AlterModelOptions(
            name='proxyemployee1',
            options={'ordering': ['-name']},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.AddField(
            model_name='employee',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
