# Generated by Django 5.0.1 on 2024-02-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgmodels', '0002_computer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='authors',
            field=models.ManyToManyField(related_name='entries', to='dgmodels.author'),
        ),
    ]
